module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER-ADMIN",
    ADMIN: "ADMIN",
  },
  USER_TYPE: {
    CREATIVE: "CREATIVE",
    USER: "USER",
  },
  SUBSCRITION_STATUS: {
    SUCCESS: "SUCCESS",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
  },
  TRANSACTION_TYPE: {
    CREDIT: "CREDIT",
    DEBIT: "DEBIT",
    WITHDRAWAL: "WITHDRAWAL",
  },
  NOTIFICATION_TYPE: {
    BOOKING_REQUEST: "BOOKING_REQUEST",
    BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
    FAILED: "FAILED",
    BOOKING_CANCELLATION: "BOOKING_CANCELLATION",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
  },
  ACCOUNT_STATUS: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    FAILED: "FAILED",
  },
};
