module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER-ADMIN",
    ADMIN: "ADMIN",
  },
  USER_TYPE: {
    SERVICE_PROVIDER: "SERVICE_PROVIDER",
    // INDIVIDUAL: "INDIVIDUAL",
    USER: "USER",
  },
  SUBSCRITION_STATUS: {
    SUCCESS: "SUCCESS",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
  },
  TRANSACTION_TYPE: {
    CREDIT: "CREDIT",
    DEBIT: "DEBIT",
    WITHDRAWAL: "WITHDRAWAL",
  },
  BOOKING_STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
  },
  NOTIFICATION_TYPE: {
    BOOKING_REQUEST: "BOOKING_REQUEST",
    BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
    FAILED: "FAILED",
    BOOKING_CANCELLATION: "BOOKING_CANCELLATION",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
  },
  SERVICE_TYPE: {
    ACCOUNTING_SERVICES: "ACCOUNTING_SERVICES",
    LEGAL_SERVICES: "LEGAL_SERVICES",
    FINANCAL_SERVICES: "FINANCAL_SERVICES"
  },
  BOARD_TYPE: {
    BLACK_BOARD: "BLACK_BOARD",
    WHITE_BOARD: "WHITE_BOARD",
  }
};
