module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER-ADMIN",
    ADMIN: "ADMIN",
  },
  USER_TYPE: {
    CREATIVE: "CREATIVE",
    USER: "USER",
  },
  SUBSCRITION_STATUS: {
    SUCCESS: "SUCCESS",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
  },
  TRANSACTION_TYPE: {
    CREDIT: "CREDIT",
    DEBIT: "DEBIT",
    WITHDRAWAL: "WITHDRAWAL",
  },
  TRANSACTION_STATUS: {
    SUCCESS: "SUCCESS",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
  },
  BARGAIN_STATUS: {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    DECLINED: "DECLINED",
    PAID: "PAID",
    COMPLETED: "COMPLETED",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
  },
  ACCOUNT_STATUS: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
  },
  LANGUAGE_PROFICIENCY: {
    BEGINNER: "BEGINNER",
    INTERMEDIATE: "INTERMEDIATE",
    ADVANCED: "ADVANCED",
  },
};
